sudo: false
dist: xenial

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -U pip setuptools wheel
  - pip install tox~=3.7.0 tox-travis tox-venv
  - python setup.py bdist_wheel

script:
  - tox

after_success:
  - pip install codecov && codecov

matrix:
  include:
    - python: 3.7
      env: TOXENV="isort,lint"

    - python: 3.7
      env: TOXENV="dist"

    - python: 3.7
      env: TOXENV="warnings"

  allow_failures:
    - env: TOXENV="warnings"
